=== OPCFoundation/UA-.NETStandard/Stack/Opc.Ua.Core/Schema/ApplicationConfiguration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ApplicationConfiguration"
    targetNamespace="http://opcfoundation.org/UA/SDK/Configuration.xsd"
    elementFormDefault="qualified"
    xmlns="http://opcfoundation.org/UA/SDK/Configuration.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:ua="http://opcfoundation.org/UA/2008/02/Types.xsd"
>
  <xs:import namespace="http://opcfoundation.org/UA/2008/02/Types.xsd" schemaLocation="./Opc.Ua.Types.xsd"/>

  <xs:complexType name="ApplicationConfiguration">
    <xs:sequence>
      <xs:element name="ApplicationName" type="xs:string" />
      <xs:element name="ApplicationUri" type="xs:string"/>
      <xs:element name="ProductUri" type="xs:string" minOccurs="0" nillable="true" />
      <xs:element name="ApplicationType" type="ua:ApplicationType" />
      <xs:element name="SecurityConfiguration" type="SecurityConfiguration" minOccurs="0" nillable="true" />
      <xs:element name="TransportConfigurations" type="ListOfTransportConfiguration" minOccurs="0" nillable="true" />
      <xs:element name="TransportQuotas" type="TransportQuotas" minOccurs="0" nillable="true" />
      <xs:element name="ServerConfiguration" type="ServerConfiguration" minOccurs="0" />
      <xs:element name="ClientConfiguration" type="ClientConfiguration" minOccurs="0" />
      <xs:element name="DiscoveryServerConfiguration" type="DiscoveryServerConfiguration" minOccurs="0" />
      <xs:element name="Extensions" type="ua:ListOfXmlElement" minOccurs="0"  />
      <xs:element name="TraceConfiguration" type="TraceConfiguration" minOccurs="0" />
      <xs:element name="DisableHiResClock" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ApplicationConfiguration" type="ApplicationConfiguration" />

  <xs:complexType name="SecurityConfiguration">
    <xs:sequence>
      <xs:element name="ApplicationCertificate" type="CertificateIdentifier" />
      <xs:element name="TrustedIssuerCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="TrustedPeerCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="NonceLength" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="RejectedCertificateStore" type="CertificateStoreIdentifier" minOccurs="0" />
      <xs:element name="AutoAcceptUntrustedCertificates" type="xs:boolean" minOccurs="0" />
      <xs:element name="UserRoleDirectory" type="xs:string"  minOccurs="0" nillable="true" />
      <xs:element name="RejectSHA1SignedCertificates" type="xs:boolean" minOccurs="0" />
      <xs:element name="RejectUnknownRevocationStatus" type="xs:boolean" minOccurs="0" />
      <xs:element name="MinimumCertificateKeySize" type="xs:unsignedShort" minOccurs="0" />
      <xs:element name="AddAppCertToTrustedStore" type="xs:boolean" minOccurs="0" />
      <xs:element name="SendCertificateChain" type="xs:boolean" minOccurs="0" />
      <xs:element name="UserIssuerCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="TrustedUserCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="HttpsIssuerCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="TrustedHttpsCertificates" type="CertificateTrustList" minOccurs="0" />
      <xs:element name="SuppressNonceValidationErrors" type="xs:boolean" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfTransportConfiguration">
    <xs:sequence>
      <xs:element name="TransportConfiguration" type="TransportConfiguration" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TransportConfiguration">
    <xs:sequence>
      <xs:element name="UriScheme" type="xs:string" />
      <xs:element name="TypeName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TransportQuotas">
    <xs:sequence>
      <xs:element name="OperationTimeout" type="xs:int" minOccurs="0" />
      <xs:element name="MaxStringLength" type="xs:int" minOccurs="0" />
      <xs:element name="MaxByteStringLength" type="xs:int" minOccurs="0" />
      <xs:element name="MaxArrayLength" type="xs:int" minOccurs="0" />
      <xs:element name="MaxMessageSize" type="xs:int" minOccurs="0" />
      <xs:element name="MaxBufferSize" type="xs:int" minOccurs="0" />
      <xs:element name="ChannelLifetime" type="xs:int" minOccurs="0" />
      <xs:element name="SecurityTokenLifetime" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ServerBaseConfiguration">
    <xs:sequence>
      <xs:element name="BaseAddresses" type="ua:ListOfString" minOccurs="0" nillable="true" />
      <xs:element name="AlternateBaseAddresses" type="ua:ListOfString" minOccurs="0" nillable="true" />
      <xs:element name="SecurityPolicies" type="ListOfServerSecurityPolicy" minOccurs="0" nillable="true" />
      <xs:element name="MinRequestThreadCount" type="xs:int" minOccurs="0" />
      <xs:element name="MaxRequestThreadCount" type="xs:int" minOccurs="0" />
      <xs:element name="MaxQueuedRequestCount" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfServerSecurityPolicy">
    <xs:sequence>
      <xs:element name="ServerSecurityPolicy" type="ServerSecurityPolicy" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ServerSecurityPolicy">
    <xs:sequence>
      <xs:element name="SecurityMode" type="ua:MessageSecurityMode" minOccurs="0" />
      <xs:element name="SecurityPolicyUri" type="xs:string" minOccurs="0"  nillable="true" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfSamplingRateGroup">
    <xs:sequence>
      <xs:element name="SamplingRateGroup" type="SamplingRateGroup" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SamplingRateGroup">
    <xs:sequence>
      <xs:element name="Start" type="xs:double" minOccurs="0" />
      <xs:element name="Increment" type="xs:double" minOccurs="0" />
      <xs:element name="Count" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ServerConfiguration">
    <xs:complexContent mixed="false">
      <xs:extension base="ServerBaseConfiguration">
        <xs:sequence>
          <xs:element name="UserTokenPolicies" type="ua:ListOfUserTokenPolicy" minOccurs="0" />
          <xs:element name="DiagnosticsEnabled" type="xs:boolean" minOccurs="0" />
          <xs:element name="MaxSessionCount" type="xs:int" minOccurs="0" />
          <xs:element name="MinSessionTimeout" type="xs:int" minOccurs="0" />
          <xs:element name="MaxSessionTimeout" type="xs:int" minOccurs="0" />
          <xs:element name="MaxBrowseContinuationPoints" type="xs:int" minOccurs="0" />
          <xs:element name="MaxQueryContinuationPoints" type="xs:int" minOccurs="0" />
          <xs:element name="MaxHistoryContinuationPoints" type="xs:int" minOccurs="0" />
          <xs:element name="MaxRequestAge" type="xs:int" minOccurs="0" />
          <xs:element name="MinPublishingInterval" type="xs:int" minOccurs="0" />
          <xs:element name="MaxPublishingInterval" type="xs:int" minOccurs="0" />
          <xs:element name="PublishingResolution" type="xs:int" minOccurs="0" />
          <xs:element name="MaxSubscriptionLifetime" type="xs:int" minOccurs="0" />
          <xs:element name="MaxMessageQueueSize" type="xs:int" minOccurs="0" />
          <xs:element name="MaxNotificationQueueSize" type="xs:int" minOccurs="0" />
          <xs:element name="MaxNotificationsPerPublish" type="xs:int" minOccurs="0" />
          <xs:element name="MinMetadataSamplingInterval" type="xs:int" minOccurs="0" />
          <xs:element name="AvailableSamplingRates" type="ListOfSamplingRateGroup" minOccurs="0" />
          <xs:element name="RegistrationEndpoint" type="ua:EndpointDescription" minOccurs="0" />
          <xs:element name="MaxRegistrationInterval" type="xs:int" minOccurs="0" />
          <xs:element name="NodeManagerSaveFile" type="xs:string" minOccurs="0" nillable="true" />
          <xs:element name="MinSubscriptionLifetime" type="xs:int" minOccurs="0" />
          <xs:element name="MaxPublishRequestCount" type="xs:int" minOccurs="0" />
          <xs:element name="MaxSubscriptionCount" type="xs:int" minOccurs="0" />
          <xs:element name="MaxEventQueueSize" type="xs:int" minOccurs="0" />
          <xs:element name="ServerProfileArray" type="ua:ListOfString" minOccurs="0" nillable="true" />
          <xs:element name="ShutdownDelay" type="xs:int" minOccurs="0" />
          <xs:element name="ServerCapabilities" type="ua:ListOfString" minOccurs="0" nillable="true" />
          <xs:element name="SupportedPrivateKeyFormats" type="ua:ListOfString" minOccurs="0" nillable="true" />
          <xs:element name="MaxTrustListSize" type="xs:int" minOccurs="0" />
          <xs:element name="MultiCastDnsEnabled" type="xs:boolean" minOccurs="0" />
          <xs:element name="ReverseConnect" type="ReverseConnectServerConfiguration" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ReverseConnectServerConfiguration">
    <xs:sequence>
      <xs:element name="Clients" type="ListOfReverseConnectClient" minOccurs="0" nillable="true" />
      <xs:element name="ConnectInterval" type="xs:int" minOccurs="0" />
      <xs:element name="ConnectTimeout" type="xs:int" minOccurs="0" />
      <xs:element name="RejectTimeout" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfReverseConnectClient">
    <xs:sequence>
      <xs:element name="ReverseConnectClient" type="ReverseConnectClient" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ReverseConnectClient">
    <xs:sequence>
      <xs:element name="EndpointUrl" type="xs:string" minOccurs="0" nillable="true" />
      <xs:element name="Timeout" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DiscoveryServerConfiguration">
    <xs:complexContent mixed="false">
      <xs:extension base="ServerBaseConfiguration">
        <xs:sequence>
          <xs:element name="ServerNames" type="ua:ListOfLocalizedText" minOccurs="0" />
          <xs:element name="DiscoveryServerCacheFile" type="xs:string" minOccurs="0" nillable="true" />
          <xs:element name="ServerRegistrations" type="ListOfServerRegistration" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ListOfServerRegistration">
    <xs:sequence>
      <xs:element name="ServerRegistration" type="ServerRegistration" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ServerRegistration">
    <xs:sequence>
      <xs:element name="ApplicationUri" type="xs:string" minOccurs="0" />
      <xs:element name="AlternateDiscoveryUrls" type="ua:ListOfString" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ClientConfiguration">
    <xs:sequence>
      <xs:element name="DefaultSessionTimeout" type="xs:int" minOccurs="0" />
      <xs:element name="WellKnownDiscoveryUrls" type="ua:ListOfString" minOccurs="0" />
      <xs:element name="DiscoveryServers" type="ua:ListOfEndpointDescription" minOccurs="0" />
      <xs:element name="EndpointCacheFilePath" type="xs:string" minOccurs="0" nillable="true" />
      <xs:element name="MinSubscriptionLifetime" type="xs:int" minOccurs="0" />
      <xs:element name="ReverseConnect" type="ReverseConnectClientConfiguration" minOccurs="0" />	  
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ReverseConnectClientConfiguration">
    <xs:sequence>
      <xs:element name="ClientEndpoints" type="ListOfReverseConnectClientEndpoint" minOccurs="0" nillable="true" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfReverseConnectClientEndpoint">
    <xs:sequence>
      <xs:element name="ClientEndpoint" type="ReverseConnectClientEndpoint" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ReverseConnectClientEndpoint">
    <xs:sequence>
      <xs:element name="EndpointUrl" type="xs:string" minOccurs="0" nillable="true" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TraceConfiguration">
    <xs:sequence>
      <xs:element name="OutputFilePath" type="xs:string" minOccurs="0" nillable="true" />
      <xs:element name="DeleteOnLoad" type="xs:boolean" minOccurs="0" />
      <xs:element name="TraceMasks" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CertificateIdentifier">
    <xs:sequence>
      <xs:element name="StoreType" type="xs:string" minOccurs="0" />
      <xs:element name="StorePath" type="xs:string" minOccurs="0" />
      <xs:element name="StoreName" type="xs:string" minOccurs="0" />
      <xs:element name="StoreLocation" type="xs:string" minOccurs="0" />
      <xs:element name="SubjectName" type="xs:string" minOccurs="0" />
      <xs:element name="Thumbprint" type="xs:string" minOccurs="0" />
      <xs:element name="RawData" type="xs:base64Binary" minOccurs="0" />
      <xs:element name="ValidationOptions" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfCertificateIdentifier">
    <xs:sequence>
      <xs:element name="CertificateIdentifier" type="CertificateIdentifier"  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CertificateStoreIdentifier">
    <xs:sequence>
      <xs:element name="StoreType" type="xs:string" minOccurs="0" />
      <xs:element name="StorePath" type="xs:string" minOccurs="0" />
      <xs:element name="StoreName" type="xs:string" minOccurs="0" />
      <xs:element name="StoreLocation" type="xs:string" minOccurs="0" />
      <xs:element name="ValidationOptions" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CertificateTrustList">
    <xs:complexContent mixed="false">
      <xs:extension base="CertificateStoreIdentifier">
        <xs:sequence>
          <xs:element name="TrustedCertificates" type="ListOfCertificateIdentifier" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ConfiguredEndpointCollection">
    <xs:sequence>
      <xs:element name="KnownHosts" type="ua:ListOfString" minOccurs="0" nillable="true" />
      <xs:element name="Endpoints" type="ListOfConfiguredEndpoint" minOccurs="0" nillable="true" />
      <xs:element name="TcpProxyUrl" type="xs:anyURI" minOccurs="0" nillable="true" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ConfiguredEndpointCollection" type="ConfiguredEndpointCollection" />

  <xs:complexType name="ListOfConfiguredEndpoint">
    <xs:sequence>
      <xs:element name="ConfiguredEndpoint" type="ConfiguredEndpoint"  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConfiguredEndpoint">
    <xs:sequence>
      <xs:element name="Endpoint" type="ua:EndpointDescription" minOccurs="0" />
      <xs:element name="Configuration" type="ua:EndpointConfiguration" minOccurs="0" />
      <xs:element name="UpdateBeforeConnect" type="xs:boolean" minOccurs="0" />
      <xs:element name="BinaryEncodingSupport" type="BinaryEncodingSupport" minOccurs="0" />
      <xs:element name="SelectedUserTokenPolicy" type="xs:int" minOccurs="0" />
      <xs:element name="UserIdentity" type="ua:UserIdentityToken" minOccurs="0" />
      <xs:element name="ComIdentity" type="EndpointComIdentity" minOccurs="0" />
	    <xs:element name="ReverseConnect" type="ReverseConnectEndpoint" minOccurs="0" />
      <xs:element name="Extensions" type="ua:ListOfXmlElement" minOccurs="0"  />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="BinaryEncodingSupport">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Optional" />
      <xs:enumeration value="Required" />
      <xs:enumeration value="None" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ReverseConnectEndpoint">
    <xs:sequence>
      <xs:element name="Enabled" type="xs:boolean" minOccurs="0" />
      <xs:element name="ServerUri" type="xs:string" minOccurs="0" />
      <xs:element name="Thumbprint" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EndpointComIdentity">
    <xs:sequence>
      <xs:element name="Clsid" type="ua:Guid" minOccurs="0" />
      <xs:element name="ProgId" type="xs:string" minOccurs="0" />
      <xs:element name="Specification" type="ComSpecification" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="ComSpecification">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DA" />
      <xs:enumeration value="AE" />
      <xs:enumeration value="HDA" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ApplicationAccessRule">
    <xs:sequence>
      <xs:element name="IdentityName" type="xs:string" minOccurs="0" />
      <xs:element name="RuleType" type="AccessControlType" minOccurs="0" />
      <xs:element name="Right" type="ApplicationAccessRight" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListOfApplicationAccessRule">
    <xs:sequence>
      <xs:element name="ApplicationAccessRule" type="ApplicationAccessRule" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="AccessControlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Allow" />
      <xs:enumeration value="Deny" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ApplicationAccessRight">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Run" />
      <xs:enumeration value="Update" />
      <xs:enumeration value="Configure" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== OPCFoundation/UA-.NETStandard/SampleApplications/Workshop/AggregatingServer/DefaultClient.Config.xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationConfiguration
  xmlns:ua="http://opcfoundation.org/UA/2008/02/Types.xsd"
  xmlns="http://opcfoundation.org/UA/SDK/Configuration.xsd"
  schemaLocation="./Schema/ApplicationConfiguration.xsd"
>
  <!-- A human readable but not necessarily unique name for the application instance -->
  <ApplicationName>DefaultClient</ApplicationName>
  
  <!-- A globally unique identifier for the application instance.
       This is overridden with the value contained in the application certificate. -->
  <ApplicationUri>urn:localhost:phi-ware:DefaultClient</ApplicationUri>
  
  <!-- A globally unique URI for the product (usually assigned by the product vendor) -->
  <ProductUri>http://phi-ware.com/UA/DefaultClient/</ProductUri>
    
  <!-- Indicates the type of application (Client, Server or ClientServer). -->
  <ApplicationType>Client_1</ApplicationType>
  
  <!-- Specifies security related configuration information -->
  <SecurityConfiguration>
    
    <!-- The location of the application instance certificate in the Windows certificate store -->
    <ApplicationCertificate>
      <StoreType>X509Store</StoreType>
      <StorePath>CurrentUser\UA_MachineDefault</StorePath>

      <!-- The subject for the certificate 
           Note that subject names are complex structures. Only text that appears here is treated as the CommonName component.
           The first certificate found is used if multiple certificates with the same CommonName and a matching hostname exist.
           Also a complete distinguished name can be specified here: 'CN=UA Sample Client, DC=localhost'.
           In this case the first certificate matching the complete distinguished name is used. localhost is replaced with the hostname.
           If no certificate is found, a new self signed application certificate is created.
           The Thumbprint should be specified if the CN or DN does not uniquely identify a certificate. -->
      <SubjectName>CN=UA Default Client, C=SK, S=Bratislava, O=phi-ware, DC=localhost</SubjectName>

      <!-- The SHA1 thumbprint for the certificate.
           The thumbprint uniquely identifies a certificate.
           It should be specified in this file, however, the samples rely on quick and 
           dirty scripts to create new certificate on each machine. A commerical application 
           would generate the initial certificate itself and update the thumbprint accordingly -->
      <!--<Thumbprint>3a35fb798fc6dee8a7e7e4652b0e28fc14c6ee0f</Thumbprint>-->
      
    </ApplicationCertificate>

    <!-- The list of certification authorities. 
    
         Typical web browsing applications trust any certificate issued by a CA in the 
         "Trusted Root Certification Authorities" certificate store. However, this approach is 
         not appropriate for UA because Adminstrators have no control over the CAs that get
         placed in that Root store to facilitate web browsing. This means Adminstrators must
         specify a different store that is used only for UA related CAs and/or they must explicitly
         specify the certificate for each trusted certification authority. -->
    <TrustedIssuerCertificates>
      <StoreType>Directory</StoreType>
      <StorePath>%CommonApplicationData%\OPC Foundation\pki\issuer</StorePath>
    </TrustedIssuerCertificates>
    
    <!-- The list of trusted certificates. 
    
         Some UA applications will use self-signed certificates (certificates without a CA)
         which means that every application which communicates with it must be configured to 
         trust it.
         
         Adminstrators may designate a certificate store that contains trusted UA application 
         instance certificates (this store should not be the same as the store used for CAs 
         certificates). Alternately, Administrators may enter the certificates explicitly in
         this list.
         
         Note that entries in this list may either reference a certificate in the store or
         may contained the entire certificate encoded as base64 data.
         -->
    <TrustedPeerCertificates>
      <StoreType>Directory</StoreType>
      <StorePath>%CommonApplicationData%\OPC Foundation\pki\trusted</StorePath>
    </TrustedPeerCertificates>
    
    <!-- Applications exchange Nonces during the CreateSession. This value specifies the length. Must be >= 32 -->
    <NonceLength>32</NonceLength>

    <!-- The directory used to store invalid certficates for later review by the administrator. -->
    <RejectedCertificateStore>
      <StoreType>Directory</StoreType>
      <StorePath>%CommonApplicationData%\OPC Foundation\pki\rejected</StorePath>
    </RejectedCertificateStore>
    
    <!-- WARNING: SHA1 signed certficates are by default rejected and should be phased out. -->
    <RejectSHA1SignedCertificates>true</RejectSHA1SignedCertificates>
    <MinimumCertificateKeySize>2048</MinimumCertificateKeySize>
    
    <!-- Specifies whether the complete certificate chain should be sent for CA signed certificates. -->
    <SendCertificateChain>false</SendCertificateChain>

    <!-- Where the User issuer certificates are stored -->
    <UserIssuerCertificates>
      <StoreType>Directory</StoreType>
      <StorePath>%CommonApplicationData%\OPC Foundation\pki\issuerUser</StorePath>
    </UserIssuerCertificates>

    <!-- Where the User trust list is stored-->
    <TrustedUserCertificates>
      <StoreType>Directory</StoreType>
      <StorePath>%CommonApplicationData%\OPC Foundation\pki\trustedUser</StorePath>
    </TrustedUserCertificates>
    <AutoAcceptUntrustedCertificates>true</AutoAcceptUntrustedCertificates>
</SecurityConfiguration>

  <TransportConfigurations></TransportConfigurations>
  
  <!-- Specifies quotas used to by the transport layer -->
  <TransportQuotas>
    
    <!-- The default timeout in milliseconds for operations (used by clients) -->
    <OperationTimeout>120000</OperationTimeout>
    
    <!-- The maximum length for a string value in any message -->
    <MaxStringLength>1048576</MaxStringLength>
    
    <!-- The maximum length for a byte string value in any message -->
    <MaxByteStringLength>4194304</MaxByteStringLength>
    
    <!-- The maximum length for any array in a message. 
         Note that some protocols do not distinguish between bytes and arrays. 
         In these cases the binding will choose the larger of 
         MaxByteStringLength or MaxArrayLength-->
    <MaxArrayLength>65535</MaxArrayLength>
    
    <!-- The maximum size of any message -->
    <MaxMessageSize>4194304</MaxMessageSize>
    
    <!-- The maximum buffer size 
         This value controls how big a block of memory the transport layer allocates.
         Setting this value to a large value will reduce performance and use a lot of RAM -->
    <MaxBufferSize>65535</MaxBufferSize>
    
    <!-- The lifetime of a SecureChannel in milliseconds.
         This specifies how long the server will keep a broken channel around while waiting 
         for a client to reconnect.
         Not used by HTTP or .NET TCP bindings -->
    <ChannelLifetime>300000</ChannelLifetime>
    
    <!-- The lifetime of a SecurityToken in milliseconds.
         This specifies how long a security token can be used without renewal. -->
    <SecurityTokenLifetime>3600000</SecurityTokenLifetime>
    
  </TransportQuotas>
  
  <!-- This element only needs to be specified for Server or ClientServer applications -->
  <ServerConfiguration>
    
    <!-- The set of addresses. One for each supported protocol.    
         Note that "localhost" is replace with the hostname when the configuration is loaded.
    
         Additional URLs are created by appending strings to the base address.
         For example, a URL used for an endpoint which uses the Basic256 security policy would look like this:
         http://localhost:61211/UA/SampleClient/Basic256Sha256 -->
    <BaseAddresses>
      <ua:String>opc.tcp://localhost:61210/UA/SampleClient</ua:String>
      <ua:String>https://localhost:61212/UA/SampleClient</ua:String>
    </BaseAddresses>

    <!-- 
    These list the alternate addresses (via firewalls, multiple NICs etc.) that can be
    used to communicate with the server. The URL used by the client when calling
    FindServers/GetEndpoints or CreateSession will be used to filter the list of
    endpoints returned by checking for alternate base addresses that have a domain
    that matches the domain in the url provided by the client.
    
    Note that any additional domains should be listed in the server's certificate. If they
    are left out the client make refuse to connect because it has no way to know if the 
    alternate domain was authorized by the server administrator.
    -->

    <!--
    <AlternateBaseAddresses>
      <ua:String>http://mycompany.com:40000/UA/SampleClient</ua:String>
    </AlternateBaseAddresses>
    -->

    <!-- The security policies supported by the server.
         
         The SDK combines these with the base address to create as many EndpointDescriptions as required.
         Protocols such as HTTP only allow one SecurityPolicy per endpoint to addition URLs are constructed
         using the SecurityPolicy and SecurityMode.
         
         The first policy in the list is assigned to base address. -->
    <SecurityPolicies>
      <ServerSecurityPolicy>
        <SecurityMode>SignAndEncrypt_3</SecurityMode>
        <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256</SecurityPolicyUri>
      </ServerSecurityPolicy>
      <!--Removing no security option from the configuration as this is a security risk
        <ServerSecurityPolicy>
        <SecurityMode>None_1</SecurityMode>
        <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#None</SecurityPolicyUri>
      </ServerSecurityPolicy>-->
      <ServerSecurityPolicy>
        <SecurityMode>Sign_2</SecurityMode>
